### ISSUE TITLE
can support wav file

### ISSUE THREAD

**Issue by z676314241** [darrena092/AudioPlayer.js#1]
![image](https://cloud.githubusercontent.com/assets/16677634/21560924/e29520e2-cea0-11e6-93ae-ace92f06f5fc.png)
![image](https://cloud.githubusercontent.com/assets/16677634/21560932/f3102278-cea0-11e6-907d-50120de89621.png)

file is ok,can download
help me

**Comment by darrena092** [comment]
Did you get this sorted? It should handle wav files just fine.
